### ISSUE TITLE
[Question] Linkis  start fail

### ISSUE THREAD

**Issue by chenliangwei3004** [apache/linkis#3477]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions
```
Begin to check cg-engineplugin
Is local execution:sh /home/chenlw/dss_linkis_one-click_install/linkis/sbin/linkis-daemon.sh status cg-engineplugin
server cg-engineplugin is not running
ERROR: your linkis-cg-engineplugin microservice is not start successful !!! ERROR logs as follows :
Please check  detail log, log path :/home/chenlw/dss_linkis_one-click_install/linkis/logs/linkis-cg-engineplugin.log
<---------------------------------------------------->
Is local execution:tail -n 50 /home/chenlw/dss_linkis_one-click_install/linkis/logs/linkis-cg-engineplugin.log
	at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$2.apply(DWSHttpClient.scala:70) ~[linkis-gateway-httpclient-support-1.1.1.jar:1.1.1]
	at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$2.apply(DWSHttpClient.scala:66) ~[linkis-gateway-httpclient-support-1.1.1.jar:1.1.1]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.12.jar:?]
	at org.apache.linkis.httpclient.dws.DWSHttpClient.httpResponseToResult(DWSHttpClient.scala:66) ~[linkis-gateway-httpclient-support-1.1.1.jar:1.1.1]
	at org.apache.linkis.httpclient.AbstractHttpClient.responseToResult(AbstractHttpClient.scala:425) ~[linkis-httpclient-1.1.1.jar:1.1.1]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:126) ~[linkis-httpclient-1.1.1.jar:1.1.1]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:92) ~[linkis-httpclient-1.1.1.jar:1.1.1]
	at org.apache.linkis.bml.client.impl.HttpBmlClient.uploadResource(HttpBmlClient.scala:313) ~[linkis-bml-client-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$uploadToBml(DefaultEngineConnResourceService.scala:59) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anonfun$org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$refresh$2.apply(DefaultEngineConnResourceService.scala:145) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anonfun$org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$refresh$2.apply(DefaultEngineConnResourceService.scala:141) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.12.jar:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$refresh(DefaultEngineConnResourceService.scala:141) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(DefaultEngineConnResourceService.scala:87) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116) ~[scala-library-2.11.12.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(DefaultEngineConnResourceService.scala:83) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(DefaultEngineConnResourceService.scala:83) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1.apply(DefaultEngineConnResourceService.scala:89) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1$$anonfun$run$1.apply(DefaultEngineConnResourceService.scala:82) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.12.jar:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.12.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.run(DefaultEngineConnResourceService.scala:82) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]

2022-09-20 18:31:59.094 [INFO ] [SpringContextShutdownHook               ] o.s.c.n.e.s.EurekaServiceRegistry (65) [deregister] - Unregistering application LINKIS-CG-ENGINEPLUGIN with eureka with status DOWN
2022-09-20 18:31:59.094 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (1352) [notify] - Saw local status change event StatusChangeEvent [timestamp=1663669919094, current=DOWN, previous=UP]
2022-09-20 18:31:59.095 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (873) [register] - DiscoveryClient_LINKIS-CG-ENGINEPLUGIN/hadoop-alone:linkis-cg-engineplugin:9103: registering service...
2022-09-20 18:31:59.108 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (882) [register] - DiscoveryClient_LINKIS-CG-ENGINEPLUGIN/hadoop-alone:linkis-cg-engineplugin:9103 - registration status: 204
2022-09-20 18:31:59.113 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.AbstractConnector (381) [doStop] - Stopped ServerConnector@740ad32e{HTTP/1.1, (http/1.1)}{0.0.0.0:9103}
2022-09-20 18:31:59.113 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.session (149) [stopScavenging] - node0 Stopped scavenging
2022-09-20 18:31:59.115 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.C.application (2363) [log] - Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-09-20 18:31:59.115 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.C.application (2363) [log] - Destroying Spring FrameworkServlet 'springrestful'
2022-09-20 18:31:59.118 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.ContextHandler (1154) [doStop] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@36d39655{application,/,[file:///tmp/jetty-docbase.9103.1865533592858738602/],STOPPED}
2022-09-20 18:31:59.120 [INFO ] [SpringContextShutdownHook               ] o.s.s.c.ThreadPoolTaskExecutor (218) [shutdown] - Shutting down ExecutorService 'applicationTaskExecutor'
2022-09-20 18:31:59.122 [INFO ] [SpringContextShutdownHook               ] c.a.d.p.DruidDataSource (2029) [close] - {dataSource-1} closing ...
2022-09-20 18:31:59.129 [INFO ] [SpringContextShutdownHook               ] c.a.d.p.DruidDataSource (2101) [close] - {dataSource-1} closed
2022-09-20 18:31:59.135 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (935) [shutdown] - Shutting down DiscoveryClient ...
2022-09-20 18:32:02.139 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (971) [unregister] - Unregistering ...
2022-09-20 18:32:02.151 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (973) [unregister] - DiscoveryClient_LINKIS-CG-ENGINEPLUGIN/hadoop-alone:linkis-cg-engineplugin:9103 - deregister  status: 200
2022-09-20 18:32:02.176 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (960) [shutdown] - Completed shut down of DiscoveryClient
```

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
can provide more detail  logs

you can refer this https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#85-%E5%A6%82%E4%BD%95%E5%AE%9A%E4%BD%8D%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%BC%82%E5%B8%B8%E6%97%A5%E5%BF%97
