### ISSUE TITLE
[Question] com.webank.wedatasphere.dss.linkis.node.execution.exception.LinkisJobExecutionErrorException: errCode: 50063 ,desc: Failed to get workspace str

### ISSUE THREAD

**Issue by zt-sjn** [apache/linkis#3736]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- DSS version used: 1.0.1
- Schedulis version used: 0.7.0
- Environment name and version:
    - cdh-6.3.2
    - hive-2.1.1
    - spark-3.0.0
    - scala-2.12.10
    - jdk 1.8.0_121
    - ....

### Describe your questions

schedulis执行dss同步的工作流任务时出现错误

### Eureka service list

![Uploading image.png…]()

### Some logs info or acctch file

任务日志
```
28-10-2022 10:43:35 CST python_2927 INFO - Starting job python_2927 at 1666925015327
28-10-2022 10:43:35 CST python_2927 INFO - job JVM args: -Dazkaban.flowid=wf02 -Dazkaban.execid=5 -Dazkaban.jobid=python_2927
28-10-2022 10:43:35 CST python_2927 INFO - Building linkis job executor. 
28-10-2022 10:43:35 CST python_2927 INFO - Start to execute job
28-10-2022 10:43:35 CST python_2927 INFO - ******   Job properties   ******
28-10-2022 10:43:35 CST python_2927 INFO - - Note : value is masked if property name ends with '_X'.
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.url=http://localhost:8081/
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.id=python_2927
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.attempt=0
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.year=2022
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.link.execution.url=http://localhost:8081/executor?execid=5
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.gateway.url.v1=http://192.168.1.36:9111/
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.gateway.url.v0=http://192.168.1.36:9111/
28-10-2022 10:43:35 CST python_2927 INFO - linkis.version=1.0.0
28-10-2022 10:43:35 CST python_2927 INFO - type=linkis
28-10-2022 10:43:35 CST python_2927 INFO - job.datachecker.jdo.option.name="job"
28-10-2022 10:43:35 CST python_2927 INFO - bdp.datachecker.jdo.option.name="bdp"
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.projectversion=4
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.minute=43
28-10-2022 10:43:35 CST python_2927 INFO - plugin.dir=/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/plugins/jobtypes/linkis
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.execid=5
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.link.workflow.url=http://localhost:8081/manager?project=pro1&flow=wf02
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.attachment.file=/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/executions/5/pro1/wf02/jobs/python_2927/_job.5.python_2927.attach
28-10-2022 10:43:35 CST python_2927 INFO - msg.eventchecker.jdo.option.name="msg"
28-10-2022 10:43:35 CST python_2927 INFO - jvm.args=-Dazkaban.flowid=wf02 -Dazkaban.execid=5 -Dazkaban.jobid=python_2927
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.uuid=7bec6acf-f8e2-45b8-85f5-70268600cbcb
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.link.jobexec.url=http://localhost:8081/executor?execid=5&job=python_2927
28-10-2022 10:43:35 CST python_2927 INFO - job.datachecker.jdo.option.username=[#DATACHECKER_JOB_USER]
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.memory.check=true
28-10-2022 10:43:35 CST python_2927 INFO - msg.eventchecker.jdo.option.password=[#DB_PASSWORD]
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.timestamp=2022-10-28T10:43:35.305+08:00
28-10-2022 10:43:35 CST python_2927 INFO - linkistype=linkis.python.python
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.link.attempt.url=http://localhost:8081/executor?execid=5&job=python_2927&attempt=0
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.milliseconds=305
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.flow.contextID={"type":"HAWorkFlowContextID","value":"{/"instance/":null,/"backupInstance/":null,/"user/":/"hadoop/",/"workspace/":/"test1/",/"project/":/"pro1/",/"flow/":/"wf02/",/"contextId/":/"8-8--cs_1_devcs_1_dev5/",/"version/":/"v000001/",/"env/":/"BDAP_DEV/"}"}
28-10-2022 10:43:35 CST python_2927 INFO - flow.dir=/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/executions/5
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.submituser=hadoop
28-10-2022 10:43:35 CST python_2927 INFO - labels={"route":"dev"}
28-10-2022 10:43:35 CST python_2927 INFO - job.datachecker.jdo.option.url=jdbc:mysql://[#DATACHECKER_JOB_IP]:[#DATACHECKER_JOB_PORT]/[#DATACHECKER_JOB_DBNAME]?useUnicode=true&characterEncoding=UTF-8
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.projectname=pro1
28-10-2022 10:43:35 CST python_2927 INFO - msg.eventchecker.jdo.option.url=jdbc:mysql://[#DB_HOST]:[#DB_PORT]/[#DB_NAME]?useUnicode=true&characterEncoding=UTF-8
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.month=10
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.native.lib=/appcom/Install/AzkabanInstall/schedulis-exec/lib
28-10-2022 10:43:35 CST python_2927 INFO - bdp.datachecker.jdo.option.username=[#DATACHECKER_BDP_USER]
28-10-2022 10:43:35 CST python_2927 INFO - msg.eventchecker.jdo.option.username=[#DB_USER]
28-10-2022 10:43:35 CST python_2927 INFO - spark.home=/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/spark3
28-10-2022 10:43:35 CST python_2927 INFO - hive.home=/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hive
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.flow.job.creator=scheduler
28-10-2022 10:43:35 CST python_2927 INFO - hadoop.home=/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hadoop
28-10-2022 10:43:35 CST python_2927 INFO - flow.variable.user.to.proxy=hadoop
28-10-2022 10:43:35 CST python_2927 INFO - bdp.datachecker.jdo.option.password=[#DATACHECKER_BDP_PWD]
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.flow.job.creator.v1=schedulis
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.hour=10
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.log.file=/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/executions/5/pro1/wf02/jobs/python_2927/_job.5.python_2927.log
28-10-2022 10:43:35 CST python_2927 INFO - user.to.proxy=hadoop
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.flowid=wf02
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.day=28
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.outnodes=wf02
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.link.job.url=http://localhost:8081/manager?project=pro1&flow=wf02&job=python_2927
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.projectlastchangedby=hadoop
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.innodes=
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.timezone=Asia/Shanghai
28-10-2022 10:43:35 CST python_2927 INFO - resources=[{"fileName":"19bc0304-e99a-4b35-8b2c-ca3fda22e609.python","resourceId":"90d50784-ac44-4e06-bc0b-ff8a1ec6b14b","version":"v000002"}]
28-10-2022 10:43:35 CST python_2927 INFO - execute.as.user=true
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.projectid=1
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.start.second=35
28-10-2022 10:43:35 CST python_2927 INFO - command={"script":"19bc0304-e99a-4b35-8b2c-ca3fda22e609.python"}
28-10-2022 10:43:35 CST python_2927 INFO - working.dir=/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/executions/5/pro1/wf02/jobs/python_2927
28-10-2022 10:43:35 CST python_2927 INFO - job.datachecker.jdo.option.password=[#DATACHECKER_JOB_PWD]
28-10-2022 10:43:35 CST python_2927 INFO - wds.linkis.client.flow.author.user.token=WS-AUTH
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.job.metadata.file=_job.5.python_2927.meta
28-10-2022 10:43:35 CST python_2927 INFO - azkaban.flow.projectlastchangeddate=1666925006461
28-10-2022 10:43:35 CST python_2927 INFO - bdp.datachecker.jdo.option.url=jdbc:mysql://[#DATACHECKER_BDP_IP]:[#DATACHECKER_BDP_PORT]/[#DATACHECKER_BDP_DBNAME]?useUnicode=true&characterEncoding=UTF-8
28-10-2022 10:43:35 CST python_2927 INFO - ****** End Job properties  ******
28-10-2022 10:43:35 CST python_2927 INFO - begin to get run date
28-10-2022 10:43:35 CST python_2927 INFO - run time is 2022-10-28T10:43:35.305+08:00
28-10-2022 10:43:35 CST python_2927 INFO - run date now is 20221028
28-10-2022 10:43:35 CST python_2927 INFO - runDate is 20221027
28-10-2022 10:43:35 CST python_2927 ERROR - Job run failed!
com.webank.wedatasphere.dss.linkis.node.execution.exception.LinkisJobExecutionErrorException: errCode: 50063 ,desc: Failed to get workspace str, responseBody is: {"timestamp":1666925015363,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/getWorkSpaceStr"} ,ip: null ,port: 0 ,serviceKind: null
	at com.webank.wedatasphere.dss.linkis.node.execution.job.Builder.getWorkspaceStr(Builder.java:141) ~[dss-linkis-node-execution-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.linkis.node.execution.job.Builder.build(Builder.java:112) ~[dss-linkis-node-execution-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.AzkabanDssJobType.run(AzkabanDssJobType.java:95) ~[?:?]
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:850) [azkaban-exec-server-0.7.0.jar:?]
	at azkaban.execapp.JobRunner.jobRunHandle(JobRunner.java:1055) [azkaban-exec-server-0.7.0.jar:?]
	at azkaban.execapp.JobRunner.jobRunHandle(JobRunner.java:1032) [azkaban-exec-server-0.7.0.jar:?]
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:605) [azkaban-exec-server-0.7.0.jar:?]
	at azkaban.execapp.JobRunner.run(JobRunner.java:562) [azkaban-exec-server-0.7.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
28-10-2022 10:43:35 CST python_2927 ERROR - errCode: 50063 ,desc: Failed to get workspace str, responseBody is: {"timestamp":1666925015363,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/getWorkSpaceStr"} ,ip: null ,port: 0 ,serviceKind: null cause: null
28-10-2022 10:43:35 CST python_2927 INFO - Finishing job python_2927 at 1666925015370 with status FAILED
```

**Comment by ruY9527** [comment]
You can upgrade the dss to version 1.1.0
You can see   1.0.1:  https://github.com/WeBankFinTech/DataSphereStudio/blob/1.0.1/dss-framework/dss-framework-workspace-server/src/main/java/com/webank/wedatasphere/dss/framework/workspace/restful/WorkspaceRestfulApi.java
