### ISSUE TITLE
[Question] EngineConnServer Start Failed. java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by kekeyin** [apache/linkis#3876]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - hdp-3.2.1
    - hive-3.1.0
    - spark-3.0.1
    - scala-2.12.10
    - jdk 1.8.0_212

### Describe your questions

执行 hive验证命令:sh bin/linkis-cli -submitUser  root  -engineType hive-3.1.0  -codeType hql  -code "show tables"
报错:EngineConnServer Start Failed. java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

检查并统一了guava和hive-exec的版本并重启后依然报错:
guava:
./home/hadoop/hadoop-3.2.1/share/hadoop/common/lib/guava-27.0-jre.jar
./home/hadoop/hadoop-3.2.1/share/hadoop/hdfs/lib/guava-27.0-jre.jar
./home/spark-3.0.1/jars/guava-27.0-jre.jar
./home/hive/lib/guava-27.0-jre.jar
./bmsys/appcom/Install/LinkisInstall/lib/linkis-commons/public-module/guava-27.0-jre.jar
./bmsys/appcom/Install/LinkisInstall/lib/linkis-spring-cloud-services/linkis-mg-gateway/guava-27.0-jre.jar

hive-exec:
./home/spark-3.0.1/jars/hive-exec-2.3.7-core.jar
./home/hive/lib/hive-exec-3.1.0.jar
./home/hive/conf/hive-exec-log4j2.properties.template
./bmsys/appcom/Install/LinkisInstall/lib/linkis-engineconn-plugins/hive/dist/v3.1.0/lib/hive-exec-3.1.0.jar
./bmsys/appcom/Install/LinkisInstall/lib/linkis-public-enhancements/linkis-ps-metadatamanager/service/hive/hive-exec-3.1.0.jar

### Eureka service list

<img width="1469" alt="WechatIMG262" src="https://user-images.githubusercontent.com/43964687/203293573-e7f73688-1894-49bd-bb6f-637d71152f86.png">

### Some logs info or acctch file

2022-11-22 16:35:17.207 ERROR [main] org.apache.linkis.engineconn.callback.service.EngineConnAfterStartCallback 46 callback - protocol will send to em: EngineConnStatusCallback(ServiceInstance(linkis-cg-engineconn, server1:36616),972c81f0-9094-4f32-84ba-8f16fa818496,Failed,ServiceInstance(linkis-cg-engineconn, server1:36616): log dir: /bmsys/appcom/tmp/root/20221122/hive/972c81f0-9094-4f32-84ba-8f16fa818496/logs,NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V)
2022-11-22 16:35:17.220 ERROR [main] org.apache.linkis.engineconn.computation.executor.hook.ComputationEngineConnHook 58 error - EngineConnSever start failed! now exit. java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357) ~[hadoop-common-3.2.1.jar:?]
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338) ~[hadoop-common-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:536) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:554) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:448) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5135) ~[hive-common-3.1.0.jar:3.1.0]
        at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5103) ~[hive-common-3.1.0.jar:3.1.0]
        at org.apache.linkis.engineplugin.hive.common.HiveUtils$.getHiveConf(HiveUtils.scala:49) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:59) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:43) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn(EngineConnFactory.scala:48) ~[linkis-engineconn-plugin-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn$(EngineConnFactory.scala:46) ~[linkis-engineconn-plugin-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConn(HiveEngineConnFactory.scala:43) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.core.engineconn.DefaultEngineConnManager.createEngineConn(EngineConnManager.scala:45) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:64) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]

2022-11-22 16:35:17.222 ERROR [main] org.apache.linkis.engineconn.core.hook.ShutdownHook 58 error - process exit reason: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357) ~[hadoop-common-3.2.1.jar:?]
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338) ~[hadoop-common-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:536) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:554) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:448) ~[hadoop-mapreduce-client-core-3.2.1.jar:?]
        at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5135) ~[hive-common-3.1.0.jar:3.1.0]
        at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5103) ~[hive-common-3.1.0.jar:3.1.0]
        at org.apache.linkis.engineplugin.hive.common.HiveUtils$.getHiveConf(HiveUtils.scala:49) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:59) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:43) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn(EngineConnFactory.scala:48) ~[linkis-engineconn-plugin-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn$(EngineConnFactory.scala:46) ~[linkis-engineconn-plugin-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConn(HiveEngineConnFactory.scala:43) ~[linkis-engineplugin-hive-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.core.engineconn.DefaultEngineConnManager.createEngineConn(EngineConnManager.scala:45) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:64) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala) ~[linkis-engineconn-core-1.1.1.jar:1.1.1]

**Comment by casionone** [comment]
refer to  https://github.com/apache/incubator-linkis/issues/2594

**Comment by Flutemr** [comment]
你好 ，请问你解决这个问题了吗？我也遇到了，我hive版本一致，自己编译的源码
