### ISSUE TITLE
[Question]The first upload of the resource failed.

### ISSUE THREAD

**Issue by Captain02** [apache/linkis#4260]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.1
- Environment name and version:
    - hdoop-3.1.3
    - hive-3.1.3
    - scala-2.12.11
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.When starting the project for the first time, the linkis-ps-publicservice report an error

### Eureka service list

![2](https://user-images.githubusercontent.com/28182876/220934409-877a968e-d11f-4cd4-81a4-e7915a49a8a3.jpg)

### Some logs info or acctch file

linkis-ps-publicservice.log:
````log
2023-02-23 21:33:50.909 [WARN ] [qtp1088034372-24                        ] o.a.h.f.FSInputChecker (165) [<init>] - Problem opening checksum file: /tmp/linkis/ltz1/bml/20230223/b8d83f60-cf6b-45a3-abf4-a373a13cb977.  Ignoring exception: java.io.EOFException: null
	at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_212]
	at java.io.DataInputStream.readFully(DataInputStream.java:169) ~[?:1.8.0_212]
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:155) ~[hadoop-common-3.1.1.jar:?]

......

2023-02-23 21:33:54.330 [INFO ] [qtp1088034372-20                        ] o.a.h.f.FSInputChecker (309) [readChecksumChunk] - Found checksum error: b[0, 0]= org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f at 82836480
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:260) ~[hadoop-common-3.1.1.jar:?]

......

2023-02-23 21:33:54.332 [ERROR] [qtp1088034372-20                        ] o.a.l.b.c.HdfsResourceHelper (97) [upload] - ltz1 write to hdfs://hdfs:///tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f failed, reason is, IOException: org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f at 82836480
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:260) ~[hadoop-common-3.1.1.jar:?]
......

2023-02-23 21:33:54.338 [ERROR] [qtp1088034372-20                        ] o.a.l.b.s.i.TaskServiceImpl (114) [createUploadTask] - Upload resource successfully. Update task (上传资源失败.更新任务) taskId:2-resourceId:013de473-cf31-4197-a012-e85a3e2f2d0f  status is   failed . org.apache.linkis.bml.common.UploadResourceException: errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice
	at org.apache.linkis.bml.common.HdfsResourceHelper.upload(HdfsResourceHelper.java:98) ~[linkis-bmlserver-1.3.1.jar:1.3.1]

......

Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f at 82836480
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:260) ~[hadoop-common-3.1.1.jar:?]
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:300) ~[hadoop-common-3.1.1.jar:?]
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:252) ~[hadoop-common-3.1.1.jar:?]
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:197) ~[hadoop-common-3.1.1.jar:?]
	at java.io.DataInputStream.read(DataInputStream.java:100) ~[?:1.8.0_212]
	at org.apache.linkis.bml.common.HdfsResourceHelper.upload(HdfsResourceHelper.java:92) ~[linkis-bmlserver-1.3.1.jar:1.3.1]
	... 129 more

......

2023-02-23 21:33:54.341 [ERROR] [qtp1088034372-20                        ] o.a.l.b.r.BmlRestfulApi (686) [uploadResource] - upload resource for user : ltz1 failed, reason: org.apache.linkis.bml.common.UploadResourceException: errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice

......

Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f at 82836480

......

Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/linkis/ltz1/bml/20230223/013de473-cf31-4197-a012-e85a3e2f2d0f at 82836480


2023-02-23 21:33:54.343 [ERROR] [qtp1088034372-20                        ] o.a.l.s.r.SpringRestfulCatchAOP (93) [apply] - error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败). org.apache.linkis.common.exception.ErrorException: errCode: 50073 ,desc: The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice
````
linkis-cg-linkismanager.log:
````log
2023-02-23 21:33:54.365 [ERROR] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.e.s.s.DefaultEngineConnResourceService (119) [apply] - Failed to upload engine conn to bml, now exit! org.apache.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"hadoop102","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"hadoop102","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: hadoop102 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: hadoop102 ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: hadoop102 ,port: 9101 ,serviceKind: linkis-cg-linkismanager
	at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:85) ~[linkis-gateway-httpclient-support-1.3.1.jar:1.3.1]


````

[linkis-cg-linkismanager.log](https://github.com/apache/linkis/files/10814522/linkis-cg-linkismanager.log)
[linkis-mg-eureka.log](https://github.com/apache/linkis/files/10814529/linkis-mg-eureka.log)
[linkis-ps-publicservice.log](https://github.com/apache/linkis/files/10814536/linkis-ps-publicservice.log)
[linkis-cg-engineconnmanager.log](https://github.com/apache/linkis/files/10814550/linkis-cg-engineconnmanager.log)
[linkis-cg-entrance.log](https://github.com/apache/linkis/files/10814553/linkis-cg-entrance.log)
[linkis-mg-gateway.log](https://github.com/apache/linkis/files/10814557/linkis-mg-gateway.log)

**Comment by casionone** [comment]
About ` org.apache.hadoop.fs.ChecksumException`  can refer to https://stackoverflow.com/questions/15434709/checksum-exception-when-reading-from-or-copying-to-hdfs-in-apache-hadoop

**Comment by Captain02** [comment]
> About ` org.apache.hadoop.fs.ChecksumException` can refer to https://stackoverflow.com/questions/15434709/checksum-exception-when-reading-from-or-copying-to-hdfs-in-apache-hadoop

After inspection, it was found that the location of the Hadoop configuration file was specified incorrectly. Although this question doesn't appear here, thank you for your answer.

**Comment by ryze124** [comment]
> > About ` org.apache.hadoop.fs.ChecksumException` can refer to https://stackoverflow.com/questions/15434709/checksum-exception-when-reading-from-or-copying-to-hdfs-in-apache-hadoop
> 
> After inspection, it was found that the location of the Hadoop configuration file was specified incorrectly. Although this question doesn't appear here, thank you for your answer.

what's your changes of hdfs-configuration?
