### ISSUE TITLE
[Question] Error: Could not find or load the main class org.apache.linkis.engineconn.launch.EngineConnServer

### ISSUE THREAD

**Issue by jetyou** [apache/linkis#4347]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - hdp-3.1.4
    - hive-3.1.0
    - jdk 1.8.0_121

### Describe your questions

Q1. 执行shell脚本出现无法加载主类错误：
t:44771), status shutting down, canRetry false, logPath /appcom/tmp/dss/20230308/shell/62f8e486-8d67-4f05-a75d-42ecc8ffc908/logs org.apache.linkis.ecm.server.exception.ECMErrorException: errCode: 11102 ,desc: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
错误: 找不到或无法加载主类 org.apache.linkis.engineconn.launch.EngineConnServer
 ,ip: ambari02.jqsoft.net ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.org$apache$linkis$ecm$server$service$impl$ProcessEngineConnLaunchService$$processMonitorThread(ProcessEngineConnLaunchService.scala:112) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply$mcV$sp(ProcessEngineConnLaunchService.scala:58) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply(ProcessEngineConnLaunchService.scala:55) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply(ProcessEngineConnLaunchService.scala:55) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.waitEngineConnStart(ProcessEngineConnLaunchService.scala:59) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply$mcV$sp(AbstractEngineConnLaunchService.scala:100) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply(AbstractEngineConnLaunchService.scala:98) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply(AbstractEngineConnLaunchService.scala:98) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_291]

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````08 16:11:59.687 [INFO ] [EngineConn-Manager-Thread-7             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (99) [apply$mcV$sp] - wait engineConn  ServiceInstance(linkis-cg-engineconn, ambari02.jqsoft.net:44771) start
2023-03-08 16:12:01.921 [INFO ] [EngineConn-Manager-Thread-8             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (96) [apply$mcV$sp] - engine 62f8e486-8d67-4f05-a75d-42ecc8ffc908 process exit 
2023-03-08 16:12:01.921 [INFO ] [EngineConn-Manager-Thread-8             ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Deal event EngineConnStatusChangeEvent(62f8e486-8d67-4f05-a75d-42ecc8ffc908,ShuttingDown)
2023-03-08 16:12:01.922 [INFO ] [EngineConn-Manager-Thread-8             ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] -  from engineConnMap to remove engineconn ticketId 62f8e486-8d67-4f05-a75d-42ecc8ffc908
2023-03-08 16:12:01.937 [INFO ] [EngineConn-Manager-Thread-8             ] o.a.l.e.s.s.i.DefaultEngineConnListService (73) [killEngineConn] - engineconn ServiceInstance(linkis-cg-engineconn, ambari02.jqsoft.net:44771) was closed.
2023-03-08 16:12:02.521 [WARN ] [EngineConn-Manager-Thread-7             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (73) [apply] - Failed to init ServiceInstance(linkis-cg-engineconn, ambari02.jqsoft.net:44771), status shutting down, canRetry false, logPath /appcom/tmp/dss/20230308/shell/62f8e486-8d67-4f05-a75d-42ecc8ffc908/logs org.apache.linkis.ecm.server.exception.ECMErrorException: errCode: 11102 ,desc: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
错误: 找不到或无法加载主类 org.apache.linkis.engineconn.launch.EngineConnServer
 ,ip: ambari02.jqsoft.net ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.org$apache$linkis$ecm$server$service$impl$ProcessEngineConnLaunchService$$processMonitorThread(ProcessEngineConnLaunchService.scala:112) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply$mcV$sp(ProcessEngineConnLaunchService.scala:58) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply(ProcessEngineConnLaunchService.scala:55) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService$$anonfun$waitEngineConnStart$1.apply(ProcessEngineConnLaunchService.scala:55) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.waitEngineConnStart(ProcessEngineConnLaunchService.scala:59) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply$mcV$sp(AbstractEngineConnLaunchService.scala:100) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply(AbstractEngineConnLaunchService.scala:98) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService$$anonfun$launchEngineConn$1$$anonfun$1.apply(AbstractEngineConnLaunchService.scala:98) ~[linkis-engineconn-manager-server-1.1.1.jar:1.1.1]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_291]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_291]
log file:
 <!-- 拖拽上传后，会自动生成如下示例格式的附件url -->
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
ls  /appcom/tmp/dss/20230308/shell/62f8e486-8d67-4f05-a75d-42ecc8ffc908/ 
see the lib directory  
grep  -r  org.apache.linkis.engineconn.launch.EngineConnServer    /appcom/tmp/dss/20230308/shell/62f8e486-8d67-4f05-a75d-42ecc8ffc908/lib

**Comment by aiceflower** [comment]
This is related to the user's own environment, which may be insufficient disk space, or it may be network reasons that the engine material package is not downloaded.
You can refer to the following paths and package names to check whether the dependency packages are complete.
![image](https://github.com/apache/linkis/assets/22620332/43f7e68b-e1d7-4f35-b07d-7d4c466d7494)

You can try again after you rule out disk and network causes.
