### ISSUE TITLE
[Question]The linkis-cli-sqoop command execute error

### ISSUE THREAD

**Issue by luckyhuke** [apache/linkis#4421]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.1
- Environment name and version:
    - hdp-3.1.3
    - hive-3.1.2
    - spark-3.0.0
    - scala-2.12.10
    - jdk 1.8.0_121
    - ....

### Describe your questions

按照sqoop引擎使用文档进行配置后运行linkis-cli-sqoop报错：

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/linkis/common/utils/Logging$class
	at org.apache.linkis.engineconn.launch.EngineConnServer$.<init>(EngineConnServer.scala:55)
	at org.apache.linkis.engineconn.launch.EngineConnServer$.<clinit>(EngineConnServer.scala)
	at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.linkis.common.utils.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

### Eureka service list

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/63639036/228232920-abf0caef-f141-4a6e-b3f7-1efa9d7e333c.png">

### Some logs info or acctch file

linkis-cg-engineconnmanager.log:

2023-03-28 19:05:13.663 [INFO ] [qtp1377456236-26                        ] o.a.l.e.s.s.i.DefaultEngineConnListService (66) [addEngineConn] - add engineConn null to engineConnMap
2023-03-28 19:05:13.666 [INFO ] [qtp1377456236-26                        ] o.a.l.e.l.l.LinuxProcessEngineConnLaunch (186) [getCommandArgs] - EUREKA_PREFER_IP: false
2023-03-28 19:05:13.668 [INFO ] [qtp1377456236-26                        ] o.a.l.e.c.l.ShellProcessEngineCommandExec (49) [execute] - Invoke subProcess, base dir /ddhome/bin/appcom/tmp/hadoop/20230328/sqoop/d4624493-58cc-469e-a5d2-88350d3945de cmd is: sudo su - hadoop -c sh /ddhome/bin/appcom/tmp/hadoop/20230328/sqoop/d4624493-58cc-469e-a5d2-88350d3945de/engineConnExec.sh
2023-03-28 19:05:13.670 [INFO ] [EngineConn-Manager-Thread-4             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (100) [$anonfun$launchEngineConn$2] - wait engineConn ServiceInstance(linkis-cg-engineconn, ddavb:42929) start
2023-03-28 19:05:14.163 [INFO ] [EngineConn-Manager-Thread-5             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (129) [$anonfun$processMonitorThread$2] - engine d4624493-58cc-469e-a5d2-88350d3945de process exit
2023-03-28 19:05:14.164 [INFO ] [EngineConn-Manager-Thread-5             ] o.a.l.e.s.s.i.DefaultEngineConnListService (151) [onEvent] - Deal event EngineConnStatusChangeEvent(d4624493-58cc-469e-a5d2-88350d3945de,ShuttingDown)
2023-03-28 19:05:14.164 [INFO ] [EngineConn-Manager-Thread-5             ] o.a.l.e.s.s.i.DefaultEngineConnListService (145) [updateEngineConnStatus] -  from engineConnMap to remove engineconn ticketId d4624493-58cc-469e-a5d2-88350d3945de
2023-03-28 19:05:14.164 [INFO ] [EngineConn-Manager-Thread-5             ] o.a.l.e.s.s.i.DefaultEngineConnListService (84) [killEngineConn] - engineconn ServiceInstance(linkis-cg-engineconn, ddavb:42929) was closed.
2023-03-28 19:05:14.276 [WARN ] [EngineConn-Manager-Thread-4             ] o.a.l.e.s.s.i.LinuxProcessEngineConnLaunchService (88) [$anonfun$waitEngineConnStart$3] - Failed to init ServiceInstance(linkis-cg-engineconn, ddavb:42929), status shutting down, canRetry false, logPath /ddhome/bin/appcom/tmp/hadoop/20230328/sqoop/d4624493-58cc-469e-a5d2-88350d3945de/logs org.apache.linkis.ecm.server.exception.ECMErrorException: errCode: 11102 ,desc: Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/linkis/common/utils/Logging$class
        at org.apache.linkis.engineconn.launch.EngineConnServer$.<init>(EngineConnServer.scala:55)
        at org.apache.linkis.engineconn.launch.EngineConnServer$.<clinit>(EngineConnServer.scala)
        at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.linkis.common.utils.Logging$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
 ,ip: ddavb ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.processMonitorThread(ProcessEngineConnLaunchService.scala:158) ~[linkis-engineconn-manager-server-1.3.1.jar:1.3.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.$anonfun$waitEngineConnStart$1(ProcessEngineConnLaunchService.scala:65) ~[linkis-engineconn-manager-server-1.3.1.jar:1.3.1]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.10.jar:?]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:47) ~[linkis-common-1.3.1.jar:1.3.1]
        at org.apache.linkis.ecm.server.service.impl.ProcessEngineConnLaunchService.waitEngineConnStart(ProcessEngineConnLaunchService.scala:66) ~[linkis-engineconn-manager-server-1.3.1.jar:1.3.1]
        at org.apache.linkis.ecm.server.service.impl.AbstractEngineConnLaunchService.$anonfun$launchEngineConn$2(AbstractEngineConnLaunchService.scala:101) ~[linkis-engineconn-manager-server-1.3.1.jar:1.3.1]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.10.jar:?]
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659) ~[scala-library-2.12.10.jar:?]
        at scala.util.Success.$anonfun$map$1(Try.scala:255) ~[scala-library-2.12.10.jar:?]
        at scala.util.Success.map(Try.scala:213) ~[scala-library-2.12.10.jar:?]
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292) ~[scala-library-2.12.10.jar:?]
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33) ~[scala-library-2.12.10.jar:?]
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33) ~[scala-library-2.12.10.jar:?]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64) ~[scala-library-2.12.10.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]

log file:

**Comment by aiceflower** [comment]
Check whether the directory of /ddhome/bin/appcom/tmp/hadoop/20230328/sqoop/d4624493-58cc-469e-a5d2-88350d3945de/logs exists or the user has read and write permission for the directory
If the verification succeeds, check the contents of the file /ddhome/bin/appcom/tmp/hadoop/20230328/sqoop/d4624493-58cc-469e-a5d2-88350d3945de/logs/stdout to confirm the error information

**Comment by casionone** [comment]
I have not replied for a long time to close first, if necessary, you can re-open.
