### ISSUE TITLE
[Bug]  Datasource client query 400 error

### ISSUE THREAD

**Issue by zhangwejun** [apache/linkis#4488]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### Steps to reproduce

1.org.apache.linkis.datasource.client.request.MetadataGetColumnsAction.Builder#build dataSourceName,database,table Unable to obtain through get method
2.org.apache.linkis.datasource.client.request.MetadataGetDatabasesAction.Builder#build
3.org.apache.linkis.datasource.client.request.MetadataGetTablesAction.Builder#build

### Expected behavior

Successfully obtained data source information

### Your environment

- Linkis version used: 1.3.1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aiceflower** [comment]
Could you paste the log to locate the problem.

**Comment by zhangwejun** [comment]
[2023-04-27 10:30:14.009][WARN ][94][com.webank.wedatasphere.exchangis.job.server.render.transform.TransformRule.toRule:83] Cannot convert to rule: [com.webank.wedatasphere.exchangis.job.server.render.transform.field.mapping.FieldMappingRuleEntity] with rule type: [MAPPING]
[2023-04-27 10:30:14.086][INFO ][94][org.apache.linkis.httpclient.dws.DWSHttpClient.org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1:159] invoke http://linkis-gateway.dev.lion/api/rest_j/v1/metadataQuery/getColumns?database=dss&system=exchangis&dataSourceName=test_linkis&table=dss_apiservice_access_info taken: 60
[2023-04-27 10:30:14.104][INFO ][91][org.apache.linkis.httpclient.dws.DWSHttpClient.org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1:159] invoke http://linkis-gateway.dev.lion/api/rest_j/v1/metadataQuery/getPartitions?system=exchangis taken: 12
[2023-04-27 10:30:14.108][ERROR][91][com.webank.wedatasphere.exchangis.datasource.server.restful.api.ExchangisDataSourceRenderRestfulApi.partition:49] Load to render partition info Failed (加载渲染分区信息失败), reason: errCode: 31018 ,desc: Fail to invoke operation: [method: getPartitionKeys, uri:metadataQuery/getPartitions], reason: errCode: 31000 ,desc: Unexpected exception in dispatching operation: [uri: metadataQuery/getPartitions, timestamp: 0] ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server com.webank.wedatasphere.exchangis.datasource.core.exception.ExchangisDataSourceException: errCode: 31018 ,desc: Fail to invoke operation: [method: getPartitionKeys, uri:metadataQuery/getPartitions], reason: errCode: 31000 ,desc: Unexpected exception in dispatching operation: [uri: metadataQuery/getPartitions, timestamp: 0] ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.rpc.LinkisDataSourceServiceRpcDispatcher.dispatch(LinkisDataSourceServiceRpcDispatcher.java:55) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.LinkisMetadataInfoService.getPartitionKeys(LinkisMetadataInfoService.java:83) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.service.impl.DefaultDataSourceRenderService.getPartitionAndRender(DefaultDataSourceRenderService.java:40) ~[exchangis-datasource-service-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.server.restful.api.ExchangisDataSourceRenderRestfulApi.partition(ExchangisDataSourceRenderRestfulApi.java:42) ~[exchangis-datasource-server-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.server.restful.api.ExchangisDataSourceRenderRestfulApi$$FastClassBySpringCGLIB$$2570fc29.invoke(<generated>) ~[exchangis-datasource-server-1.1.1.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.linkis.server.restful.SpringRestfulCatchAOP$$anonfun$1.apply(SpringRestfulCatchAOP.scala:43) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.server.restful.SpringRestfulCatchAOP$$anonfun$1.apply(SpringRestfulCatchAOP.scala:43) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:47) ~[linkis-common-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.server.package$.catchMsg(package.scala:76) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.server.package$.catchIt(package.scala:116) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.server.restful.SpringRestfulCatchAOP.dealResponseRestful(SpringRestfulCatchAOP.scala:42) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at com.webank.wedatasphere.exchangis.datasource.server.restful.api.ExchangisDataSourceRenderRestfulApi$$EnhancerBySpringCGLIB$$3c27e428.partition(<generated>) ~[exchangis-datasource-server-1.1.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) ~[websocket-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.apache.linkis.server.security.SecurityFilter.doFilter(SecurityFilter.scala:124) ~[linkis-module-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97) ~[spring-boot-actuator-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) ~[jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
Caused by: com.webank.wedatasphere.exchangis.datasource.core.exception.ExchangisServiceRpcException: errCode: 31000 ,desc: Unexpected exception in dispatching operation: [uri: metadataQuery/getPartitions, timestamp: 0] ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.datasource.core.service.rpc.AbstractServiceRpcDispatcher.dispatch(AbstractServiceRpcDispatcher.java:31) ~[exchangis-datasource-core-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.rpc.LinkisDataSourceServiceRpcDispatcher.dispatch(LinkisDataSourceServiceRpcDispatcher.java:53) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	... 105 more
Caused by: org.apache.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/metadataQuery/getPartitions request failed! ResponseBody is {"timestamp":1682562614101,"status":400,"error":"Bad Request","message":"","path":"/api/rest_j/v1/metadataQuery/getPartitions"}. errCode: 10905 ,desc: URL /api/rest_j/v1/metadataQuery/getPartitions request failed! ResponseBody is {"timestamp":1682562614101,"status":400,"error":"Bad Request","message":"","path":"/api/rest_j/v1/metadataQuery/getPartitions"}. ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server ,ip: 10.42.9.132 ,port: 9321 ,serviceKind: exchangis-server
	at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:85) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:84) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:61) ~[linkis-common-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.dws.response.DWSResult$class.set(DWSResult.scala:84) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.datasource.client.response.MetadataGetPartitionsResult.set(MetadataGetPartitionsResult.scala:30) ~[linkis-datasource-client-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:83) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:79) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:?]
	at org.apache.linkis.httpclient.dws.DWSHttpClient.httpResponseToResult(DWSHttpClient.scala:79) ~[linkis-gateway-httpclient-support-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.AbstractHttpClient$$anonfun$responseToResult$2.apply(AbstractHttpClient.scala:536) ~[linkis-httpclient-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.AbstractHttpClient$$anonfun$responseToResult$2.apply(AbstractHttpClient.scala:479) ~[linkis-httpclient-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:69) ~[linkis-common-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.AbstractHttpClient.responseToResult(AbstractHttpClient.scala:548) ~[linkis-httpclient-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:173) ~[linkis-httpclient-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:127) ~[linkis-httpclient-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at org.apache.linkis.datasource.client.AbstractRemoteClient.execute(AbstractRemoteClient.scala:28) ~[linkis-datasource-client-2.0.0-3.1.5.0-152.jar:2.0.0-3.1.5.0-152]
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.rpc.LinkisDataSourceServiceRpcDispatcher.execute(LinkisDataSourceServiceRpcDispatcher.java:25) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.rpc.LinkisDataSourceServiceRpcDispatcher.execute(LinkisDataSourceServiceRpcDispatcher.java:16) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.core.service.rpc.AbstractServiceRpcDispatcher.dispatch(AbstractServiceRpcDispatcher.java:25) ~[exchangis-datasource-core-1.1.1.jar:?]
	at com.webank.wedatasphere.exchangis.datasource.linkis.service.rpc.LinkisDataSourceServiceRpcDispatcher.dispatch(LinkisDataSourceServiceRpcDispatcher.java:53) ~[exchangis-datasource-linkis-1.1.1.jar:?]
	... 105 more
