### ISSUE TITLE
Unable to start embedded Jetty server

### ISSUE THREAD

**Issue by liuzj-github** [apache/linkis#4532]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2
- Environment name and version:
    - mrs-3.2.0
    - hive-3.1.0-h0.cbu.mrs.320.r11
    - spark-.1.1-h0.cbu.mrs.320.r11
    - scala-2.12.15
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  ..执行linkis-cli-hive,无法启动hive引擎服务，Unable to start embedded Jetty server，经排查是hive-exec依赖包javax.servlet.jsp与linkis的jetty发生冲突，不知道怎么解决

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->
2023-05-10 10:40:03.040 ERROR jobRequest(LINKISCLI_drmp_hive_3)  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: 172.38.110.125:9101_0 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, 172.38.110.125:37008) ticketID:e6f45d87-6a2b-41a5-9cf9-ecb97b795282 Failed to initialize engine, reason: Failed to start EngineConn, reason: ECMErrorException: errCode: 11102 ,desc: 10:40:01.556 ERROR org.springframework.boot.SpringApplication 834 reportFailure - Application run failed org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.apache.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:111) ~[linkis-module-1.3.2.jar:1.3.2]
	at org.apache.linkis.engineconn.callback.hook.CallbackEngineConnHook.beforeCreateEngineConn(CallbackEngineConnHook.scala:60) ~[linkis-accessible-executor-1.3.2.jar:1.3.2]
	at org.apache.linkis.engineconn.launch.EngineConnServer$.$anonfun$main$1(EngineConnServer.scala:85) ~[linkis-engineconn-core-1.3.2.jar:1.3.2]
	at org.apache.linkis.engineconn.launch.EngineConnServer$.$anonfun$main$1$adapted(EngineConnServer.scala:85) ~[linkis-engineconn-core-1.3.2.jar:1.3.2]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) ~[scala-library-2.12.15.jar:?]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) ~[scala-library-2.12.15.jar:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198) ~[scala-library-2.12.15.jar:?]
	at org.apache.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:85) ~[linkis-engineconn-core-1.3.2.jar:1.3.2]
	at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala) ~[linkis-engineconn-core-1.3.2.jar:1.3.2]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:194) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	... 20 more
Caused by: java.lang.IllegalStateException
	at org.eclipse.jetty.servlet.ServletHolder.setClassFrom(ServletHolder.java:300) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:347) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:1.8.0_332]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_332]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_332]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313) ~[?:1.8.0_332]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[?:1.8.0_332]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_332]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:774) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:233) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:169) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
Can you list the conflicting jar packages?
with file path and package name
such as 
```
linkis/lib/linkis-engineconn-plugins/spark/dist/2.3.0/lib/jetty-security-9.4.48.v20220622.jar
xxxx
···

**Comment by liuzj-github** [comment]
问题解决，降低jetty版本

**Comment by ryze124** [comment]
> 问题解决，降低jetty版本

jetty降到哪个版本？
