### ISSUE TITLE
[Bug] queresource search failed

### ISSUE THREAD

**Issue by CharlieYan24** [apache/linkis#4660]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

2023-06-16 14:51:25.741 [ERROR] [qtp12691277-558                         ] o.a.l.m.r.r.RMMonitorRest (688) [getQueueResource] [JobId-] - queresource search failed! org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server versio
n for the right syntax to use near ')' at line 2
### The error may exist in URL [jar:file:/data/Install/LinkisInstall/LinkisInstall140/lib/linkis-computation-governance/linkis-cg-linkismanager/linkis-manager-persistence
-1.4.0-SNAPSHOT.jar!/mapper/common/NodeManagerMapper.xml]
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to 
use near ')' at line 2
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server v
ersion for the right syntax to use near ')' at line 2
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.2.23.RELEASE.jar:5
.2.23.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.23.RELEASE.
jar:5.2.23.RELEASE]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91) ~[mybatis-spring-2.0.6.jar:2.0.6]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441) ~[mybatis-spring-2.0.6.jar:2.0.6]
        at com.sun.proxy.$Proxy147.selectList(Unknown Source) ~[?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224) ~[mybatis-spring-2.0.6.jar:2.0.6]
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166) ~[mybatis-plus-core-3.4.3.4.jar:3.4.3.4]
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77) ~[mybatis-plus-core-3.4.3.4.jar:3.4.3.4]
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148) ~[mybatis-plus-core-3.4.3.4.jar:3.4.3.4]
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89) ~[mybatis-plus-core-3.4.3.4.jar:3.4.3.4]
        at com.sun.proxy.$Proxy151.getNodeInstancesByOwnerList(Unknown Source) ~[?:?]
        at org.apache.linkis.manager.persistence.impl.DefaultNodeManagerPersistence.getNodesByOwnerList(DefaultNodeManagerPersistence.java:356) ~[linkis-manager-persisten
ce-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
        at org.apache.linkis.manager.rm.restful.RMMonitorRest.getEngineNodesByUserList(RMMonitorRest.java:819) ~[linkis-application-manager-1.4.0-SNAPSHOT.jar:1.4.0-SNAPS
HOT]
        at org.apache.linkis.manager.rm.restful.RMMonitorRest.getQueueResource(RMMonitorRest.java:607) ~[linkis-application-manager-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
        at org.apache.linkis.manager.rm.restful.RMMonitorRest$$FastClassBySpringCGLIB$$1633b070.invoke(<generated>) ~[linkis-application-manager-1.4.0-SNAPSHOT.jar:1.4.0-
SNAPSHOT]

### Expected behavior

getEngineNodesByUserList success.

### Your environment

- Linkis version used: 1.4.0
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
same to https://github.com/apache/linkis/issues/4643
