### ISSUE TITLE
Executing Datax node in workflow, engine task execution successful but node prompts execution failure

### ISSUE THREAD

**Issue by tuigerphkeeper** [apache/linkis#4873]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

linkis-1.4.0
dss-1.1.2
scala-2.11.12

### Describe your questions

在工作流中执行datax节点，datax任务执行成功，但是节点状态为执行失败。
<img width="1133" alt="image" src="https://github.com/apache/linkis/assets/42008109/9543e8fd-2225-47ef-8306-0e6342cd15c5">

### Eureka service list

<img width="1444" alt="image" src="https://github.com/apache/linkis/assets/42008109/ab00e102-baab-44c2-b46d-eac8e0a4df43">

### Some logs info or acctch file

stdout:
````log
2023-08-25 15:20:53.983 INFO  [job-1906365927952355328] com.alibaba.datax.core.job.JobContainer 197 start - 
         [total cpu info] => 
                averageCpu                     | maxDeltaCpu                    | minDeltaCpu                    
                -1.00%                         | -1.00%                         | -1.00%
                        

         [total gc info] => 
                 NAME                 | totalGCCount       | maxDeltaGCCount    | minDeltaGCCount    | totalGCTime        | maxDeltaGCTime     | minDeltaGCTime     
                 G1 Young Generation  | 13                 | 13                 | 13                 | 0.320s             | 0.320s             | 0.320s             
                 G1 Old Generation    | 0                  | 0                  | 0                  | 0.000s             | 0.000s             | 0.000s             

2023-08-25 15:20:53.983 INFO  [job-1906365927952355328] com.alibaba.datax.core.job.JobContainer 200 start - PerfTrace not enable!
2023-08-25 15:20:53.984 INFO  [job-1906365927952355328] com.alibaba.datax.core.statistics.container.communicator.job.StandAloneJobContainerCommunicator 54 report - Total 48384 records, 1344846 bytes | Speed 262.67KB/s, 9676 records/s | Erro
r 0 records, 0 bytes |  All task WaitWriterTime 2.643s |  All task WaitReaderTime 1.414s | Percentage 100.00%
2023-08-25 15:20:53.984 INFO  [job-1906365927952355328] com.alibaba.datax.core.job.JobContainer 703 logStatistics - 
任务启动时刻                    : 2023-08-25 15:20:41
任务结束时刻                    : 2023-08-25 15:20:53
任务总计耗时                    :                 12s
任务平均流量                    :          262.67KB/s
记录写入速度                    :           9676rec/s
读出记录总数                    :               48384
读写失败总数                    :                   0

2023-08-25 15:20:53.985 INFO  [job-1906365927952355328] org.apache.linkis.engineconnplugin.datax.executor.DataxJobOnceExecutor 47 info - The executor: [DataxOnceApp_Job-Container_0]  has been finished, now to stop DataxEngineConn.
2023-08-25 15:20:53.985 WARN  [job-1906365927952355328] org.apache.linkis.engineconnplugin.datax.executor.DataxJobOnceExecutor 197 trySucceed - DataxOnceApp_Job-Container_0 has succeed with old status Running, now stop it.
2023-08-25 15:20:53.986 INFO  [job-1906365927952355328] org.apache.linkis.engineconnplugin.datax.executor.DataxJobOnceExecutor 60 transition - org.apache.linkis.engineconnplugin.datax.executor.DataxJobOnceExecutor@40589959 changed status Ru
nning => Success.
````
log file:
[stdout.txt](https://github.com/apache/linkis/files/12436710/stdout.txt)
linkis-cg-entrance.log
````log
2023-08-25 15:20:58.546 [WARN ] [RPC-Receiver-Asyn-Thread-Thread-0       ] o.a.l.o.c.s.ComputationTaskExecutionReceiver (138) [taskResultSizeReceiver] [JobId-] - from ServiceInstance(linkis-cg-engineconn, lc-node1:42293) received ResponseTaskResultSize(1,0) cannot find execTask to deal
2023-08-25 15:20:58.583 [INFO ] [RPC-Receiver-Asyn-Thread-Thread-0       ] o.a.l.r.MessageReceiver (35) [receive] [JobId-] - From caller ServiceInstance(linkis-cg-engineconn, lc-node1:42293) get async message
2023-08-25 15:20:58.583 [INFO ] [RPC-Receiver-Asyn-Thread-Thread-0       ] o.a.l.r.MessageReceiver (40) [receiveAndReply] [JobId-] - From caller ServiceInstance(linkis-cg-engineconn, lc-node1:42293) get sync message
2023-08-25 15:20:58.583 [WARN ] [RPC-Receiver-Asyn-Thread-Thread-0       ] o.a.l.o.c.s.ComputationTaskExecutionReceiver (107) [taskStatusReceiver] [JobId-] -  from ServiceInstance(linkis-cg-engineconn, lc-node1:42293) received ResponseTaskStatus(1,Succeed) cannot find execTask to deal
2023-08-25 15:21:08.583 [WARN ] [RPC-Receiver-Asyn-Thread-Thread-0       ] o.a.l.o.c.s.ComputationTaskExecutionReceiver (110) [taskStatusReceiver] [JobId-] -  from ServiceInstance(linkis-cg-engineconn, lc-node1:42293) received ResponseTaskStatus(1,Succeed) cannot find execTask to deal, by retry 2 times
2023-08-25 15:21:39.196 [INFO ] [Linkis-Default-Scheduler-Thread-2       ] o.a.l.o.e.i.BaseTaskScheduler (50) [apply$mcV$sp] [JobId-] - Clear finished task from  taskFutureCache size 0
````
exchangis.log
````log
2023-08-25 15:20:47.983 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-10  ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/executeEngineConnOperation taken: 1.5 s.
2023-08-25 15:20:47.984 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-10  ] o.a.l.c.c.o.i.EngineConnProgressOperator (79) [apply] - hadoop asked EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnProgress operation, results is {progress=0.0, progressInfo=[{succeedTasks=0, failedTasks=0, id=null, totalTasks=0, runningTasks=0}]} .
2023-08-25 15:20:50.649 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-3   ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/getEngineConn taken: 13 ms.
2023-08-25 15:20:50.650 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-3   ] o.a.l.c.c.o.i.EngineConnMetricsOperator (72) [apply] - hadoop try to ask EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnMetrics operation, parameters is {"instance":"lc-node1:35409","parameters":{"__operator_name__":"engineConnMetrics"},"applicationName":"linkis-cg-engineconn","ticketId":"75d1cda7-a3e1-4eb3-adfd-2f570533c9aa"}.
2023-08-25 15:20:50.666 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-3   ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/executeEngineConnOperation taken: 16 ms.
2023-08-25 15:20:50.666 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-3   ] o.a.l.c.c.o.i.EngineConnMetricsOperator (79) [apply] - hadoop asked EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnMetrics operation, results is {metrics={NodeResourceJson={"memory":10.0 GB,"cpu":1}}} .
2023-08-25 15:20:50.669 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-3   ] c.w.w.e.j.s.l.DefaultRpcJobLogger$ (23) [onEvent] - [hadoop:d54aaa3f-6f0b-49e3-9c6e-4b6b14e5a060] Metrics info of task: [{"NodeResourceJson":"{\"memory\":10.0 GB,\"cpu\":1}"}]
2023-08-25 15:20:50.964 [INFO ] [Balancer-ThreadFlexibleTenancyLoadBalancer] c.w.w.e.j.s.e.l.FlexibleTenancyLoadBalancer (189) [lambda$loop$2] - Monitor: [tenancy: hadoop, task_segments: 15, wait_in_poll: 2]
2023-08-25 15:20:52.986 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-9   ] c.w.w.e.j.s.e.s.t.StatusUpdateSchedulerTask (34) [onPoll] - Status update task: [1906365927952355328] in scheduler: [Multi-Tenancy-Group-hadoop_0_7-Status]
2023-08-25 15:20:52.996 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-9   ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/getEngineConn taken: 10 ms.
2023-08-25 15:20:52.997 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-9   ] o.a.l.c.c.o.i.EngineConnProgressOperator (72) [apply] - hadoop try to ask EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnProgress operation, parameters is {"instance":"lc-node1:35409","parameters":{"__operator_name__":"engineConnProgress"},"applicationName":"linkis-cg-engineconn","ticketId":"75d1cda7-a3e1-4eb3-adfd-2f570533c9aa"}.
2023-08-25 15:20:53.014 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-9   ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/executeEngineConnOperation taken: 17 ms.
2023-08-25 15:20:53.015 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-9   ] o.a.l.c.c.o.i.EngineConnProgressOperator (79) [apply] - hadoop asked EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnProgress operation, results is {progress=0.0, progressInfo=[{succeedTasks=0, failedTasks=0, id=null, totalTasks=0, runningTasks=0}]} .
2023-08-25 15:20:53.678 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-16  ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/getEngineConn taken: 8 ms.
2023-08-25 15:20:53.678 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-16  ] o.a.l.c.c.o.i.EngineConnMetricsOperator (72) [apply] - hadoop try to ask EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnMetrics operation, parameters is {"instance":"lc-node1:35409","parameters":{"__operator_name__":"engineConnMetrics"},"applicationName":"linkis-cg-engineconn","ticketId":"75d1cda7-a3e1-4eb3-adfd-2f570533c9aa"}.
2023-08-25 15:20:53.696 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-16  ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/executeEngineConnOperation taken: 17 ms.
2023-08-25 15:20:53.696 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-16  ] o.a.l.c.c.o.i.EngineConnMetricsOperator (79) [apply] - hadoop asked EngineConn(ServiceInstance(linkis-cg-engineconn, lc-node1:35409)) to execute engineConnMetrics operation, results is {metrics={NodeResourceJson={"memory":10.0 GB,"cpu":1}}} .
2023-08-25 15:20:53.698 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-16  ] c.w.w.e.j.s.l.DefaultRpcJobLogger$ (23) [onEvent] - [hadoop:d54aaa3f-6f0b-49e3-9c6e-4b6b14e5a060] Metrics info of task: [{"NodeResourceJson":"{\"memory\":10.0 GB,\"cpu\":1}"}]
2023-08-25 15:20:53.964 [INFO ] [Balancer-ThreadFlexibleTenancyLoadBalancer] c.w.w.e.j.s.e.l.FlexibleTenancyLoadBalancer (189) [lambda$loop$2] - Monitor: [tenancy: hadoop, task_segments: 15, wait_in_poll: 2]
2023-08-25 15:20:56.710 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-15  ] o.a.l.h.d.DWSHttpClient (160) [org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1] - invoke http://lc-node2:9001/api/rest_j/v1/linkisManager/getEngineConn taken: 12 ms.
2023-08-25 15:20:56.965 [INFO ] [Balancer-ThreadFlexibleTenancyLoadBalancer] c.w.w.e.j.s.e.l.FlexibleTenancyLoadBalancer (189) [lambda$loop$2] - Monitor: [tenancy: hadoop, task_segments: 15, wait_in_poll: 2]
2023-08-25 15:20:58.016 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-5   ] c.w.w.e.j.s.e.s.t.StatusUpdateSchedulerTask (34) [onPoll] - Status update task: [1906365927952355328] in scheduler: [Multi-Tenancy-Group-hadoop_0_3-Status]
2023-08-25 15:20:58.021 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-5   ] c.w.w.e.j.s.e.DefaultTaskManager (35) [info] - Progress of task: [1906365927952355328] change 0.0 => 1.0
2023-08-25 15:20:58.021 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-5   ] c.w.w.e.j.s.l.DefaultRpcJobLogger$ (23) [onEvent] - [hadoop:d54aaa3f-6f0b-49e3-9c6e-4b6b14e5a060] Progress of task: [1906365927952355328] change 0.0 => 1.0
2023-08-25 15:20:58.021 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-5   ] c.w.w.e.j.s.e.DefaultTaskManager (35) [info] - Status of task: [name: JKPypTZWwtnF, id: 1906365927952355328] change Running => Success
2023-08-25 15:20:58.021 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-5   ] c.w.w.e.j.s.l.DefaultRpcJobLogger$ (23) [onEvent] - [hadoop:d54aaa3f-6f0b-49e3-9c6e-4b6b14e5a060] Status of task: [name: JKPypTZWwtnF, id: 1906365927952355328] change Running => Success
````

dss-server.log
````log
2023-08-25 15:20:35.174 INFO  [pool-4-thread-20] org.apache.linkis.httpclient.dws.DWSHttpClient 160 org$apache$linkis$httpclient$AbstractHttpClient$$addAttempt$1 - invoke http://172.18.0.59:9001/api/rest_j/v1/jobhistory/146/get taken: 6 ms.
2023-08-25 15:20:35.175 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.node.DefaultNodeRunner 47 info - from state Running to Failed
2023-08-25 15:20:35.175 ERROR [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 73 error - Failed to execute node(datax_1460),prepare to kill flow job
2023-08-25 15:20:35.177 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.service.impl.WorkflowQueryServiceImpl 47 info - Update data to the database(往数据库中更新数据)：RequestPersistTask{taskID=759, instance='l
c-node2:9043', execId='flowexecution_hadoop_flowexecution_23', umUser='hadoop', engineInstance='null', executionCode='null', progress=0.0, logPath='hdfs:///appcom/logs/linkis/log/2023-08-25/flowexecution/hadoop/759.log', resultLocation='nul
l', status='Running', createdTime=Fri Aug 25 15:20:19 CST 2023, updatedTime=Fri Aug 25 15:20:35 CST 2023, errCode=31001, errDesc='用户主动kill任务', executeApplicationName='null', requestApplicationName='null', source={projectName=project00
2, flowName=w1}, runType='flowexecution', params={workspace=Workspace{workspaceId=224, workspaceName='bdapWorkspace', cookies={linkis_user_session_ticket_id_v1=M7UZXQP9Ld0N3KLqio9suw7o1fouVhAO2HLiVea4FcQ=, dataworkcloud_inner_request=true, 
workspaceName=bdapWorkspace, language=zh_CN, workspaceId=224}, dssUrl='http://lc-node2:9001'}, configuration={runtime={wds.linkis.resultSet.store.path=hdfs:///tmp/linkis/hadoop/linkis/2023-08-25/152019/flowexecution/759}}, executeStrategy=s
electedExecute, nodeID=a382a881-5d9f-4b30-a1f7-4aa1123d0f8c, labels=dev}}
2023-08-25 15:20:35.179 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 97 onFailure - job jobGroupId:759 execID:flowexecution_hadoop_flowexecution_23 is onFailure on state Running with error
Msg: Job is killed by user!.
2023-08-25 15:20:35.179 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 127 onFailure - jobGroupId:759 execID:flowexecution_hadoop_flowexecution_23 execute failed. Reason: Job is killed by us
er!.
2023-08-25 15:20:35.180 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 97 transition - jobGroupId:759 execID:flowexecution_hadoop_flowexecution_23 change status Running => Failed.
2023-08-25 15:20:35.181 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.service.impl.WorkflowQueryServiceImpl 47 info - Update data to the database(往数据库中更新数据)：RequestPersistTask{taskID=759, instance='l
c-node2:9043', execId='flowexecution_hadoop_flowexecution_23', umUser='hadoop', engineInstance='null', executionCode='null', progress=1.0, logPath='hdfs:///appcom/logs/linkis/log/2023-08-25/flowexecution/hadoop/759.log', resultLocation='nul
l', status='Failed', createdTime=Fri Aug 25 15:20:19 CST 2023, updatedTime=Fri Aug 25 15:20:35 CST 2023, errCode=31001, errDesc='用户主动kill任务', executeApplicationName='null', requestApplicationName='null', source={projectName=project002
, flowName=w1}, runType='flowexecution', params={workspace=Workspace{workspaceId=224, workspaceName='bdapWorkspace', cookies={linkis_user_session_ticket_id_v1=M7UZXQP9Ld0N3KLqio9suw7o1fouVhAO2HLiVea4FcQ=, dataworkcloud_inner_request=true, w
orkspaceName=bdapWorkspace, language=zh_CN, workspaceId=224}, dssUrl='http://lc-node2:9001'}, configuration={runtime={wds.linkis.resultSet.store.path=hdfs:///tmp/linkis/hadoop/linkis/2023-08-25/152019/flowexecution/759}}, executeStrategy=se
lectedExecute, nodeID=a382a881-5d9f-4b30-a1f7-4aa1123d0f8c, labels=dev}}
2023-08-25 15:20:35.184 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.service.impl.WorkflowQueryServiceImpl 47 info - Update data to the database(往数据库中更新数据)：RequestPersistTask{taskID=759, instance='l
c-node2:9043', execId='flowexecution_hadoop_flowexecution_23', umUser='hadoop', engineInstance='null', executionCode='null', progress=1.0, logPath='hdfs:///appcom/logs/linkis/log/2023-08-25/flowexecution/hadoop/759.log', resultLocation='nul
l', status='Failed', createdTime=Fri Aug 25 15:20:19 CST 2023, updatedTime=Fri Aug 25 15:20:35 CST 2023, errCode=31001, errDesc='用户主动kill任务', executeApplicationName='null', requestApplicationName='null', source={projectName=project002
, flowName=w1}, runType='flowexecution', params={workspace=Workspace{workspaceId=224, workspaceName='bdapWorkspace', cookies={linkis_user_session_ticket_id_v1=M7UZXQP9Ld0N3KLqio9suw7o1fouVhAO2HLiVea4FcQ=, dataworkcloud_inner_request=true, w
orkspaceName=bdapWorkspace, language=zh_CN, workspaceId=224}, dssUrl='http://lc-node2:9001'}, configuration={runtime={wds.linkis.resultSet.store.path=hdfs:///tmp/linkis/hadoop/linkis/2023-08-25/152019/flowexecution/759}}, executeStrategy=se
lectedExecute, nodeID=a382a881-5d9f-4b30-a1f7-4aa1123d0f8c, labels=dev}}
2023-08-25 15:20:35.184 INFO  [pool-4-thread-20] org.apache.linkis.entrance.job.EntranceExecutionJob 258 close - job:759 is closing
2023-08-25 15:20:35.185 INFO  [pool-4-thread-20] org.apache.linkis.entrance.log.HDFSCacheLogWriter 65 close -  hdfs:///appcom/logs/linkis/log/2023-08-25/flowexecution/hadoop/759.log logWriter close
2023-08-25 15:20:35.185 INFO  [dss-server-dev-EventListenerBus-Thread-0] org.apache.linkis.entrance.EntranceWebSocketService 303 apply - retMessage: execID is 131313flowexecutionflowexecutionlc-node2:9043flowexecution_hadoop_flowexecution_2
3, status is Failed, websocketTag is null
2023-08-25 15:20:35.185 INFO  [pool-4-thread-20] org.apache.linkis.entrance.log.HDFSCacheLogWriter 115 writeToFile - hdfs:///appcom/logs/linkis/log/2023-08-25/flowexecution/hadoop/759.log write first one line log
2023-08-25 15:20:35.209 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 47 info - Succeed to kill flow job
2023-08-25 15:20:35.209 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.job.FlowEntranceJob 47 info - This Flow(flowexecution_hadoop_flowexecution_23) is Completed
2023-08-25 15:20:35.209 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.node.DefaultNodeRunner 47 info - Finished to execute node of datax_1460
2023-08-25 15:20:35.209 INFO  [pool-4-thread-20] com.webank.wedatasphere.dss.flow.execution.entrance.execution.NodeExecutionStatusPoller 47 info - node datax_1460 status is completed
2023-08-25 15:20:35.280 INFO  [qtp1497194297-417] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowEntranceRestfulApi 138 status - Begin to get status for execId:exec_id014013dss-server-devlc-node2:9043flowexecution_hadoop_fl
owexecution_23
2023-08-25 15:20:35.280 INFO  [qtp1497194297-417] org.apache.linkis.server.utils.ModuleUserUtils 68 getProxyUserEntity - user hadoop proxy to null operation status realId: flowexecution_hadoop_flowexecution_23
2023-08-25 15:20:35.281 INFO  [qtp1497194297-417] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowEntranceRestfulApi 174 status - End to get status for execId:exec_id014013dss-server-devlc-node2:9043flowexecution_hadoop_flow
execution_23
2023-08-25 15:20:35.474 INFO  [qtp1497194297-345] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowExecutionRestfulApi 62 execution - Begin to get job execution info, id:exec_id014013dss-server-devlc-node2:9043flowexecution_h
adoop_flowexecution_23
2023-08-25 15:20:35.474 INFO  [qtp1497194297-345] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowExecutionRestfulApi 68 execution - Start to get job flowexecution_hadoop_flowexecution_23 execution info
2023-08-25 15:20:35.477 INFO  [qtp1497194297-345] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowExecutionRestfulApi 122 execution - End to get job execution info, id:exec_id014013dss-server-devlc-node2:9043flowexecution_hadoop_flowexecution_23
2023-08-25 15:20:35.581 INFO  [qtp1497194297-370] com.webank.wedatasphere.dss.flow.execution.entrance.restful.FlowExecutionRestfulApi 62 execution - Begin to get job execution info, id:exec_id014013dss-server-devlc-node2:9043flowexecution_hadoop_flowexecution_23
````
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
There is nothing wrong with the log, @aiceflower  please help to troubleshoot

**Comment by aiceflower** [comment]
Is it inevitable or occasional? Can you describe the recurrence process?

**Comment by tuigerphkeeper** [comment]
inevitable。Create a new workflow, add a datax node, configure the collection of information, and it can be executed normally on the Exchange side. In the workflow, the collection was successful but the node failed。

**Comment by tuigerphkeeper** [comment]
inevitable。Create a new workflow, add a datax node, configure the collection of information, and it can be executed normally on the Exchange side. In the workflow, the collection was successful but the node failed。必现。新建工作流，添加datax节点，配置采集信息，在exchangis那边可以正常执行，在工作流里面执行采集成功但是节点失败。

**Comment by tuigerphkeeper** [comment]
<img width="952" alt="image" src="https://github.com/apache/linkis/assets/42008109/5abbbc76-1e62-490d-b711-c47d0c13b70d">

**Comment by tuigerphkeeper** [comment]
<stderr.log>

16:26:34.938 ERROR org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$submitASyncTask$2 316 apply - Failed to submit task1 scala.MatchError: null
        at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$2$$anonfun$3.apply(ComputationExecutor.scala:266) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$2$$anonfun$3.apply(ComputationExecutor.scala:264) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.async.AsyncConcurrentComputationExecutor.ensureOp(AsyncConcurrentComputationExecutor.scala:185) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$2.apply(ComputationExecutor.scala:264) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$2.apply(ComputationExecutor.scala:256) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:77) ~[linkis-common-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.execute(ComputationExecutor.scala:281) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$submitASyncTask$1.apply(TaskExecutionServiceImpl.scala:314) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$submitASyncTask$1.apply(TaskExecutionServiceImpl.scala:314) ~[linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:49) [linkis-common-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl.submitASyncTask(TaskExecutionServiceImpl.scala:315) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl.submitTask(TaskExecutionServiceImpl.scala:300) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl.org$apache$linkis$engineconn$computation$executor$service$TaskExecutionServiceImpl$$submitTaskToExecutor(TaskExecutionServiceImpl.scala:266) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$execute$2$$anon$1$$anonfun$run$1.apply$mcV$sp(TaskExecutionServiceImpl.scala:234) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$execute$2$$anon$1$$anonfun$run$1.apply(TaskExecutionServiceImpl.scala:230) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$execute$2$$anon$1$$anonfun$run$1.apply(TaskExecutionServiceImpl.scala:230) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:49) [linkis-common-1.4.0.jar:1.4.0]
        at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anonfun$execute$2$$anon$1.run(TaskExecutionServiceImpl.scala:242) [linkis-computation-engineconn-1.4.0.jar:1.4.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_333]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_333]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_333]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_333]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]

**Comment by aiceflower** [comment]
Is your appconn plug-in up to date? You need scala 1.12 + to compile appconn.

**Comment by tuigerphkeeper** [comment]
> Is your appconn plug-in up to date? You need scala 1.12 + to compile appconn.

I am using Spark2.3.0, and the scala version can only use 2.11

**Comment by tuigerphkeeper** [comment]
Resolved。The ComputationExecutor class execute method in linkis1.4.0 is missing one other type match, plus case _=> That's fine。
<img width="669" alt="image" src="https://github.com/apache/linkis/assets/42008109/251629ed-6c8c-449c-8364-b18eb640c1b6">
