### ISSUE TITLE
[Bug] ERROR [qtp1058155740-54] org.apache.linkis.manager.am.restful.EngineRestfulApi 323 createEngineConn - User xxxxx create engineConn failed

### ISSUE THREAD

**Issue by lizhenning** [apache/linkis#4968]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.4.0
- Exchangis version used:1.1.2
- Environment name and version:
    - Operation System:MacOS
    - IDE: IDEA
    - jdk 1.8.0_212
    

### Describe your questions

在exchangis中提交一个datax数据同步任务，在linkis-cg-linkismanager应用中报错如下:
`ERROR [qtp1058155740-54] org.apache.linkis.manager.am.restful.EngineRestfulApi 323 createEngineConn - User lizhenning create engineConn failed. org.apache.linkis.rpc.exception.NoInstanceExistsException: errCode: 10051 ,desc: The instance:lizhenningdembp:9102 of application linkis-cg-engineconnmanager does not exist(应用程序:lizhenningdembp:9102 的实例:linkis-cg-engineconnmanager 不存在). ,ip: lizhenningdembp ,port: 9101 ,serviceKind: linkis-cg-linkismanager
`

### Eureka service list

相关的服务都已经启动了：

![image](https://github.com/apache/linkis/assets/8910473/6fc896ff-e8da-4310-88b7-cf6a05262651)

### Some logs info or acctch file

linkis-cg-linkismanager.log:
````2023-11-15 21:19:28.864 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:29.371 INFO  [qtp1058155740-26] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:30.870 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:31.376 INFO  [qtp1058155740-26] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:32.872 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:33.382 INFO  [qtp1058155740-26] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:34.873 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:35.386 INFO  [qtp1058155740-26] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:36.879 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:37.391 INFO  [qtp1058155740-26] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:38.883 INFO  [qtp1058155740-54] org.apache.linkis.rpc.sender.spring.SpringRPCServerLoader 82 $anonfun$getOrRefresh$2 - Need a ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102), but cannot find in DiscoveryClient refresh list.
2023-11-15 21:19:38.883 INFO  [qtp1058155740-54] org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService 193 createEngine - Failed to create ec(9823c3ea-d041-46af-9d7c-835455a7e47e) ask ecm ServiceInstance(linkis-cg-engineconnmanager, lizhenningdembp:9102)
2023-11-15 21:19:38.889 INFO  [qtp1058155740-54] org.apache.linkis.manager.am.service.engine.DefaultEngineStopService 207 engineConnInfoClear - Start to clear ec info AMEngineNode{nodeStatus=Failed, lock='null', serviceInstance=ServiceInstance(linkis-cg-engineconn, 9823c3ea-d041-46af-9d7c-835455a7e47e), owner='null'}
2023-11-15 21:19:38.895 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 62 tryLock - successfully locked labellinkis-cg-engineconn-9823c3ea-d041-46af-9d7c-835455a7e47e
2023-11-15 21:19:38.898 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.impl.DefaultResourceManager 650 lambda$resourceReleased$11 - resourceRelease ready:ServiceInstance(linkis-cg-engineconn, 9823c3ea-d041-46af-9d7c-835455a7e47e),current node resourceCommonNodeResource{resourceType=LoadInstance, maxResource=Number of instances(实例数)：1，(RAM)内存：1 ,cpu: 1073741824, minResource=Number of instances(实例数)：1，(RAM)内存：1 ,cpu: 1073741824, usedResource=null, lockedResource=Number of instances(实例数)：1，(RAM)内存：1 ,cpu: 1073741824, expectedResource=null, leftResource=null}
2023-11-15 21:19:38.905 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 62 tryLock - successfully locked labellinkis-cg-engineconnmanager-lizhenningdembp:9102
2023-11-15 21:19:38.916 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 71 lambda$unLock$2 - unlocked linkis-cg-engineconnmanager-lizhenningdembp:9102
2023-11-15 21:19:38.922 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 62 tryLock - successfully locked labellizhenning-exchangis,datax-3.0.0
2023-11-15 21:19:38.933 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 71 lambda$unLock$2 - unlocked lizhenning-exchangis,datax-3.0.0
2023-11-15 21:19:38.946 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.impl.ResourceLogService 126 success - EngineResourceClear success, 
2023-11-15 21:19:38.949 INFO  [qtp1058155740-54] org.apache.linkis.manager.rm.service.ResourceLockService 71 lambda$unLock$2 - unlocked linkis-cg-engineconn-9823c3ea-d041-46af-9d7c-835455a7e47e
2023-11-15 21:19:38.950 INFO  [qtp1058155740-54] org.apache.linkis.manager.label.service.impl.DefaultNodeLabelRemoveService 54 removeNodeLabel - Start to remove labels from node ServiceInstance(linkis-cg-engineconn, 9823c3ea-d041-46af-9d7c-835455a7e47e)
2023-11-15 21:19:38.960 INFO  [qtp1058155740-54] org.apache.linkis.manager.label.service.impl.DefaultNodeLabelRemoveService 78 removeNodeLabel - Finished to remove labels from node ServiceInstance(linkis-cg-engineconn, 9823c3ea-d041-46af-9d7c-835455a7e47e)
2023-11-15 21:19:38.967 INFO  [qtp1058155740-54] org.apache.linkis.manager.am.service.engine.DefaultEngineStopService 227 engineConnInfoClear - Finished to clear ec info AMEngineNode{nodeStatus=Failed, lock='null', serviceInstance=ServiceInstance(linkis-cg-engineconn, 9823c3ea-d041-46af-9d7c-835455a7e47e), owner='null'}
2023-11-15 21:19:38.967 ERROR [qtp1058155740-54] org.apache.linkis.manager.am.restful.EngineRestfulApi 323 createEngineConn - User lizhenning create engineConn failed. org.apache.linkis.rpc.exception.NoInstanceExistsException: errCode: 10051 ,desc: The instance:lizhenningdembp:9102 of application linkis-cg-engineconnmanager does not exist(应用程序:lizhenningdembp:9102 的实例:linkis-cg-engineconnmanager 不存在). ,ip: lizhenningdembp ,port: 9101 ,serviceKind: linkis-cg-linkismanager
	at org.apache.linkis.rpc.interceptor.AbstractRPCServerLoader.getOrRefresh(RPCServerLoader.scala:71) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.AbstractRPCServerLoader.getServer(RPCServerLoader.scala:108) ~[classes/:?]
	at org.apache.linkis.rpc.sender.SpringMVCRPCSender$$anon$1$$anon$2.$anonfun$customizeLoadBalancerCommandBuilder$6(SpringMVCRPCSender.scala:114) ~[classes/:?]
	at scala.Option.foreach(Option.scala:407) ~[scala-library-2.12.17.jar:?]
	at org.apache.linkis.rpc.sender.SpringMVCRPCSender$$anon$1$$anon$2.customizeLoadBalancerCommandBuilder(SpringMVCRPCSender.scala:112) ~[classes/:?]
	at org.apache.linkis.rpc.sender.SpringMVCRPCSender$$anon$1$$anon$2.customizeLoadBalancerCommandBuilder(SpringMVCRPCSender.scala:73) ~[classes/:?]
	at com.netflix.client.AbstractLoadBalancerAwareClient.buildLoadBalancerCommand(AbstractLoadBalancerAwareClient.java:132) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:94) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:84) ~[spring-cloud-openfeign-core-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-10.12.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:?]
	at com.sun.proxy.$Proxy220.receiveAndReply(Unknown Source) ~[?:?]
	at org.apache.linkis.rpc.BaseRPCSender.$anonfun$ask$1(BaseRPCSender.scala:94) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.BaseRPCInterceptorExchange.invoke(RPCInterceptorExchange.scala:30) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.common.CommonRPCInterceptor.intercept(CommonRPCInterceptor.scala:35) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:40) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.common.RetryableRPCInterceptor.intercept(RetryableRPCInterceptor.scala:64) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:40) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.common.CacheableRPCInterceptor.intercept(CacheableRPCInterceptor.scala:85) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:40) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.common.BroadcastRPCInterceptor.intercept(BroadcastRPCInterceptor.scala:86) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:40) ~[classes/:?]
	at org.apache.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:87) ~[classes/:?]
	at org.apache.linkis.rpc.BaseRPCSender.ask(BaseRPCSender.scala:91) ~[classes/:?]
	at org.apache.linkis.manager.am.pointer.DefaultEMNodPointer.createEngine(DefaultEMNodPointer.java:58) ~[classes/:?]
	at org.apache.linkis.manager.am.manager.DefaultEMNodeManager.createEngine(DefaultEMNodeManager.java:206) ~[classes/:?]
	at org.apache.linkis.manager.am.service.em.DefaultEMEngineService.createEngine(DefaultEMEngineService.java:86) ~[classes/:?]
	at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.java:191) ~[classes/:?]
	at org.apache.linkis.manager.am.restful.EngineRestfulApi.createEngineConn(EngineRestfulApi.java:314) ~[classes/:?]
	at org.apache.linkis.manager.am.restful.EngineRestfulApi$$FastClassBySpringCGLIB$$355728e5.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.apache.linkis.server.restful.SpringRestfulCatchAOP.$anonfun$dealResponseRestful$1(SpringRestfulCatchAOP.scala:43) ~[classes/:?]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:49) ~[classes/:?]
	at org.apache.linkis.server.package$.catchMsg(package.scala:76) ~[classes/:?]
	at org.apache.linkis.server.package$.catchIt(package.scala:116) ~[classes/:?]
	at org.apache.linkis.server.restful.SpringRestfulCatchAOP.dealResponseRestful(SpringRestfulCatchAOP.scala:42) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.apache.linkis.manager.am.restful.EngineRestfulApi$$EnhancerBySpringCGLIB$$e04e363.createEngineConn(<generated>) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1043) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292) ~[websocket-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.apache.linkis.server.security.SecurityFilter.doFilter(SecurityFilter.scala:124) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:45) ~[knife4j-spring-2.0.9.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97) ~[spring-boot-actuator-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
Caused by: java.util.concurrent.TimeoutException
	at org.apache.linkis.common.utils.Utils$.aux$1(Utils.scala:251) ~[classes/:?]
	at org.apache.linkis.common.utils.Utils$.waitUntil(Utils.scala:256) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.AbstractRPCServerLoader.$anonfun$getOrRefresh$1(RPCServerLoader.scala:89) ~[classes/:?]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.17.jar:?]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:49) ~[classes/:?]
	at org.apache.linkis.common.utils.Utils$.tryThrow(Utils.scala:74) ~[classes/:?]
	at org.apache.linkis.rpc.interceptor.AbstractRPCServerLoader.getOrRefresh(RPCServerLoader.scala:91) ~[classes/:?]
	... 132 more


<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/linkis/files/9219529/yarn-error.log)

**Comment by peacewong** [comment]
This is due to the fact that ECM service does not exist. You can restart the service
这个看是ECM服务不存在导致，你可以重启下该服务
