### ISSUE TITLE
[Bug] [1.5.0] The error message of starting cg-linkismanager caused by the token problem is not user-friendly, it needs to be optimized

### ISSUE THREAD

**Issue by gjy1043** [apache/linkis#5042]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nacos.common.notify.NotifyCenter
        at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:92) ~[nacos-client-2.1.0.jar:?]
        at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81) ~[nacos-client-2.1.0.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.1.0.jar:?]
        at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.1.0.jar:?]
        at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        ... 20 more

### Expected behavior

Error information is clear and unambiguous

### Your environment

- Linkis version used: 1.5.0
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
> caused by the token problem

Does this happen when the nacos username and password are configured incorrectly?

**Comment by wForget** [comment]
Are there more `Caused by` in the error stack?

**Comment by peacewong** [comment]
For detailed logs, please refer to stdout. 
[stdout.log](https://github.com/apache/linkis/files/13696687/stdout.log)
