### ISSUE TITLE
[Bug] postgresql jdbc url create connection SQLException

### ISSUE THREAD

**Issue by xieshaoqiang** [apache/linkis#5129]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

DSS 1.1.2 + LINKIS 1.4.0
创建数据源 
<img width="930" alt="d26fa1ba620b43d3d4cb8a3f7aba7f1" src="https://github.com/apache/linkis/assets/102786769/9b521018-0ee3-4635-aa91-1dfbadafd5f2">
Scriptis 执行jdbc脚本，下拉选择创建好的数据源
<img width="930" alt="2ff7718e19d5f6588e66e29a2492a81" src="https://github.com/apache/linkis/assets/102786769/46293384-456a-4835-a9fc-2ae3851e1429">
JDBC URL 组装缺少了数据库名称，导致连接失败
2024-06-24 16:04:13.717 ERROR [Druid-ConnectionPool-Create-848259924] com.alibaba.druid.pool.DruidDataSource 2912 run [JobId-] - create connection SQLException, url: jdbc:postgresql://192.168.0.229:5432?stringtype=unspecified, errorCode 0, state 99999 org.postgresql.util.PSQLException: Unable to parse URL jdbc:postgresql://192.168.0.229:5432?stringtype=unspecified
	at org.postgresql.Driver.connect(Driver.java:274) ~[postgresql-42.5.4.jar:42.5.4]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1701) ~[druid-1.2.16.jar:?]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1786) ~[druid-1.2.16.jar:?]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2910) ~[druid-1.2.16.jar:?]
2024-06-24 16:04:13.728 WARN  [Druid-ConnectionPool-Create-87671547] org.postgresql.Driver 558 parseURL [JobId-] - JDBC URL must contain a / at the end of the host or port: jdbc:postgresql://192.168.0.229:5432
2024-06-24 16:04:13.728 ERROR [Druid-ConnectionPool-Create-87671547] com.alibaba.druid.pool.DruidDataSource 2912 run [JobId-] - create connection SQLException, url: jdbc:postgresql://192.168.0.229:5432, errorCode 0, state 99999 org.postgresql.util.PSQLException: Unable to parse URL jdbc:postgresql://192.168.0.229:5432
	at org.postgresql.Driver.connect(Driver.java:274) ~[postgresql-42.5.4.jar:42.5.4]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1701) ~[druid-1.2.16.jar:?]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1786) ~[druid-1.2.16.jar:?]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2910) ~[druid-1.2.16.jar:?]
2024-06-24 16:04:13.004 ERROR jobRequest(IDE_hadoop_jdbc_14)  execute failed,21304, Task is Failed,errorMsg: created data source connection error! 
2024-06-24 16:04:13.004 INFO Task creation time(任务创建时间): 2024-06-24 16:04:13, Task scheduling time(任务调度时间): 2024-06-24 16:04:13, Task start time(任务开始时间): 2024-06-24 16:04:13, Mission end time(任务结束时间): 2024-06-24 16:04:13
2024-06-24 16:04:13.004 INFO Task submit to Orchestrator time:2024-06-24 16:04:13, Task request EngineConn time:2024-06-24 16:04:13, Task submit to EngineConn time:2024-06-24 16:04:13
2024-06-24 16:04:13.004 INFO Your mission(您的任务) 52 The total time spent is(总耗时时间为): 110 ms
2024-06-24 16:04:13.004 INFO Sorry. Your job completed with a status Failed. You can view logs for the reason.
2024-06-24 16:04:13.004 INFO job is completed.

### Expected behavior

JDBC脚本执行成功

### Your environment

- Linkis version used: 1.4.0
- Environment name and version:
    - jdbc4
    - ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
You can add my WeChat: peaceAyton

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量

**Comment by zhang-arvin** [comment]
I will work on this.
